// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bpximszuewhbtotswsng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJweGltc3p1ZXdoYnRvdHN3c25nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MDM5NjAsImV4cCI6MjA2NDI3OTk2MH0.pxyE2mIj-_l9-1ohMjm5D4rHfybytXNxtJWO27Xb4As";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});